### ISSUE TITLE
ElasticsearchEngine: replicas and shards config

### ISSUE THREAD

**Issue by SpyWSamara** [sigmie/elasticsearch-scout#2]
There is looks like some typo in `\Sigmie\ElasticsearchScout\ElasticsearchEngine` class:

https://github.com/sigmie/elasticsearch-scout/blob/59a217f6e40b66acbb4ad0940f6a144ee463a673/src/ElasticsearchEngine.php#L37-L38

and

https://github.com/sigmie/elasticsearch-scout/blob/59a217f6e40b66acbb4ad0940f6a144ee463a673/src/ElasticsearchEngine.php#L96-L97

In configuration file we can set two parameters `replicas` and `shards`:

https://github.com/sigmie/elasticsearch-scout/blob/59a217f6e40b66acbb4ad0940f6a144ee463a673/config/elasticsearch-scout.php#L17-L19

But in code `shards` parameter will be ignored. It will be `replicas` only parameter in use.

**Comment by nicoorfi** [comment]
It's fixed in v1.0.0 ✅
